declare class Vector {
    x: number;
    y: number;
    z: number;
    constructor(x?: number, y?: number, z?: number);
    negative(): Vector;
    add(v: Vector | number): Vector;
    subtract(v: Vector | number): Vector;
    multiply(v: Vector | number): Vector;
    divide(v: Vector | number): Vector;
    equals(v: Vector): boolean;
    dot(v: Vector): number;
    cross(v: Vector): Vector;
    length(): number;
    unit(): Vector;
    min(): number;
    max(): number;
    toAngles(): {
        theta: number;
        phi: number;
    };
    angleTo(a: Vector): number;
    toArray(n?: number): number[];
    clone(): Vector;
    init(x: number, y: number, z: number): this;
    static negative(a: Vector, b: Vector): Vector;
    static add(a: Vector, b: Vector | number, c: Vector): Vector;
    static subtract(a: Vector, b: Vector | number, c: Vector): Vector;
    static multiply(a: Vector, b: Vector | number, c: Vector): Vector;
    static divide(a: Vector, b: Vector | number, c: Vector): Vector;
    static cross(a: Vector, b: Vector, c: Vector): Vector;
    static unit(a: Vector, b: Vector): Vector;
    static fromAngles(theta: number, phi: number): Vector;
    static randomDirection(): Vector;
    static min(a: Vector, b: Vector): Vector;
    static max(a: Vector, b: Vector): Vector;
    static lerp(a: Vector, b: Vector, fraction: number): Vector;
    static fromArray(a: number[]): Vector;
    static angleBetween(a: Vector, b: Vector): number;
}
export { Vector };
